### ISSUE TITLE
Required Pandas library crashes GUI if updated to latest

### ISSUE THREAD

**Issue by nbonacchi** [pybpod/pybpod#103]
**Describe the bug**
pybpod-gui uses pandas 0.something latest version is 1.3.3
Other dependencies of rig environments require a higher version of pandas and this makes the GUI crash on Stop protocol. 
Pybpod tries to write stuff to the json files and pandas complains

I guess this is a sub-issue of #102 meaning update python version + dependencies, 3.9 would be awesome :stuck_out_tongue_closed_eyes: 

**To Reproduce**
1. pip update pandas
2. Run a task
3. Press Stop

**Desktop (please complete the following information):**
 - OS: [ Windows 10 latest]
 - PyBpod version [e.g. 1.8.2]

**Additional context**
Can look up the precise error if you need it

**Comment by micheleangelofabbri** [comment]
To add to this, with Python v3.7 and the latest version of pandas we get this error after pressing 'Stop' during a run of habituationCW:

```
2022-08-25 13:23:02.944 INFO     [_iblrig_tasks_habituationChoiceWorld.py:67] Starting trial: 9
main
Traceback (most recent call last):
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 253, in run_task_handler
    self.end_run_task_handler()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_plugin\models\board\board_com.py", line 68, in end_run_task_handler
    super(BoardCom, self).end_run_task_handler()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 291, in end_run_task_handler
    session.load_contents()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_plugin\models\session\session_window.py", line 83, in load_contents
    super(SessionWindow, self).load_contents()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_api\models\session\session_io.py", line 114, in load_contents
    memory_map=True
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1914, in pandas._libs.parsers.raise_parser_error
ValueError: I/O operation on closed file.
```

Interestingly, when we switch over to Python v3.8 and run the same task we get the following error:
```
C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\habituationChoiceWorld\sessions\202208~2\20220829-102428.csv - The process cannot access the file because it is being used by another process.
Traceback (most recent call last):
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '+INFO'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 253, in run_task_handler
    self.end_run_task_handler()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_plugin\models\board\board_com.py", line 68, in end_run_task_handler
    super(BoardCom, self).end_run_task_handler()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 291, in end_run_task_handler
    session.load_contents()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_plugin\models\session\session_window.py", line 83, in load_contents
    super(SessionWindow, self).load_contents()
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pybpodgui_api\models\session\session_io.py", line 119, in load_contents
    self.ended = date_parser.parse(row['+INFO'])
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\core\series.py", line 958, in __getitem__
    return self._get_value(key)
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\core\series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\IBLuser\anaconda3\envs\iblrig\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: '+INFO'
```

This generally looks like an issue with accessing a file that is in the process of being moved from one directory to another?

Digging in a bit when we look at the 20220829-102428.csv file that it is complaining about, the '+INFO' key is actually a '+INFO\r'. This may not be the actual issue here, but I am a bit confused as to why that is even happening. This looks like half of a Windows new line '\r\n' sneaking its way into the csv file even though this sca (https://pypi.org/project/safe-and-collaborative-architecture/) package looks to be specifying the new line to simply be '\n' when attempting to output to a csv. 

Any help would be much appreciated on this.
